#!/usr/bin/env bash
#
# This file is part of the kiagnose project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Copyright 2023 Red Hat, Inc.
#

set -e

# Disable unnecessary services
disable_services() {
  local service_list=("NetworkManager-wait-online" "sshd")
  for service in "${service_list[@]}"; do
    systemctl disable "$service"
  done
}

# Install trex package
install_trex() {
  local TREX_URL=https://trex-tgn.cisco.com/trex/release
  local TREX_VERSION=v3.03
  local TREX_ARCHIVE_NAME=${TREX_VERSION}.tar.gz
  local TREX_DIR=/opt/trex

  mkdir -p ${TREX_DIR}
  cd ${TREX_DIR}

  curl --insecure ${TREX_URL}/${TREX_ARCHIVE_NAME} --output ${TREX_ARCHIVE_NAME}

  tar -xzf ${TREX_ARCHIVE_NAME} --strip-components=1

  rm ${TREX_ARCHIVE_NAME}
}

# Setup hugepages in cmdline
setup_hugepages() {
  mkdir -p /mnt/huge
  echo "hugetlbfs /mnt/huge hugetlbfs defaults,pagesize=1GB 0 0" >> /etc/fstab

  grubby --update-kernel=ALL --args="default_hugepagesz=1GB hugepagesz=1G hugepages=1"
}

# Enable unsafe noiommu mode
set_unsafe_no_io_mmu_mode() {
  echo "options vfio enable_unsafe_noiommu_mode=1" > /etc/modprobe.d/vfio-noiommu.conf
}

disable_services
setup_hugepages
install_trex
set_unsafe_no_io_mmu_mode
